baseURL = "https://matthieugouel.name"
title = "Matthieu Gouel"
theme = "m10c"
enableEmoji = true

[pagination]
pagerSize = 10

[menu]
[[menu.main]]
identifier = "about"
name = "About me"
url = "/about/"
weight = 2

[params]
author = "Matthieu Gouel"
avatar = "avatar.png"
description = "Systems Engineer @Cloudflare"
menu_item_separator = " - "
[[params.social]]
icon = "mail"
name = "Mail"
url = "mailto:matthieu.gouel@protonmail.com"
[[params.social]]
icon = "github"
name = "Github"
url = "https://github.com/matthieugouel"
[[params.social]]
icon = "book"
name = "Scholar"
url = "https://scholar.google.fr/citations?user=Ltb5srIAAAAJ&hl=fr&oi=ao"

[params.style]
darkestColor = "#010408"
darkColor = "#0D1116"
lightColor = "#afbac4"
lightestColor = "#ffffff"
primaryColor = "#f6f6f6"
